cc_test(
    name = "hueReadFile",
    srcs = ["hueReadFile.c"],
    deps = ["//huec:lib"],
)

cc_test(
    name = "hueParseHelloWorld",
    srcs = ["hueParseHelloWorld.c"],
    deps = ["//huec:lib"],
)

cc_test(
    name = "hueEvalHelloWorld",
    srcs = ["hueEvalHelloWorld.c"],
    deps = ["//huec:lib"],
)
