cc_test(
    name = "hueReadFile",
    srcs = ["hueReadFile.c"],
    deps = ["//huec:lib"],
    timeout = "short",
)

cc_test(
    name = "helloWorld",
    srcs = ["helloWorld.c"],
    deps = ["//huec:lib"],
    timeout = "short",
)

cc_test(
    name = "add",
    srcs = ["add.c"],
    deps = ["//huec:lib"],
    timeout = "short",
)
