# Library
cc_library(
    name = "lib",
    srcs = ["io.c", "ast.c", "parser.c", "val.c", "eval.c"],
    hdrs = ["lib.h", "io.h", "ast.h", "parser.h", "val.h", "eval.h"],

    visibility = ["//test:__pkg__"],
)
